# Generated by Django 4.2.16 on 2024-11-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "restaurants_food_category",
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="restaurants/items/images/")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "food_type",
                    models.CharField(
                        choices=[("veg", "Vegetarian"), ("non-veg", "Non-Vegetarian")],
                        default="non-veg",
                        max_length=10,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="food_items", to="restaurants.category"
                    ),
                ),
            ],
            options={
                "db_table": "restaurants_food_items",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("featured_image", models.ImageField(upload_to="restaurants/images/")),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("outlet", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("working_days", models.JSONField()),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("offer_text", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="restaurants", to="restaurants.category"
                    ),
                ),
            ],
            options={
                "db_table": "restaurants_restaurant",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=15)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("food_items", models.ManyToManyField(to="restaurants.fooditem")),
            ],
            options={
                "db_table": "restaurants_order",
            },
        ),
        migrations.AddField(
            model_name="fooditem",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_items",
                to="restaurants.restaurant",
            ),
        ),
    ]
