# Generated by Django 4.2.16 on 2024-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="delivery_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="working_days",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
