# Generated by Django 4.2.16 on 2024-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_restaurant_delivery_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="images",
            field=models.ImageField(upload_to="food_items/images/"),
        ),
    ]
