# Generated by Django 4.2.16 on 2024-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
