# Generated by Django 4.2.16 on 2024-12-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_restaurant_owner_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["id"]},
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
