# Generated by Django 4.2.16 on 2025-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_restaurant_owner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(to="restaurants.category"),
        ),
    ]
