# Generated by Django 4.2.16 on 2025-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_alter_category_name_alter_restaurant_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="is_deleted",
            new_name="is_available",
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="images",
            field=models.ImageField(null=True, upload_to="food_items/images/"),
        ),
    ]
