# Generated by Django 4.2.16 on 2025-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0012_locations_delete_collection_restaurant_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
