# Generated by Django 4.2.16 on 2024-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                    ("restaurant_owner", "Restaurant Owner"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
