# Generated by Django 4.2.16 on 2025-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
