# Generated by Django 4.2.16 on 2025-01-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_alter_restaurant_options_delete_order"),
        ("orders", "0004_remove_order_customer_name_order_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.fooditem",
            ),
            preserve_default=False,
        ),
    ]
