# Generated by Django 4.2.16 on 2025-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_order_order_id_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
